#!/bin/sh

# ENV
exec > /root/firs-setup.log 2>&1

msg() {
    local DATE=$(date '+%d %B %Y %T')
    echo "[ INFO FIRST SETUP ] $1"
    logger -p "notice" "[ INFO FIRST SETUP ] $1"
}

# dont remove!
msg "Installed Time: $(date '+%A, %d %B %Y %T')"
msg "###############################################"
msg "Processor: $(ubus call system board | grep '\"system\"' | sed 's/ \+/ /g' | awk -F'\"' '{print $4}')"
msg "Device Model: $(ubus call system board | grep '\"model\"' | sed 's/ \+/ /g' | awk -F'\"' '{print $4}')"
msg "Device Board: $(ubus call system board | grep '\"board_name\"' | sed 's/ \+/ /g' | awk -F'\"' '{print $4}')"
sed -i "s#_('Firmware Version'),(L.isObject(boardinfo.release)?boardinfo.release.description+' / ':'')+(luciversion||''),#_('Firmware Version'),(L.isObject(boardinfo.release)?boardinfo.release.description+' build by RTA-WRT [ Ouc3kNF6 ]':''),#g" /www/luci-static/resources/view/status/include/10_system.js
sed -i -E "s|icons/port_%s.png|icons/port_%s.gif|g" /www/luci-static/resources/view/status/include/29_ports.js
sed -i 's/\[ -f \/etc\/banner \] && cat \/etc\/banner/#&/' /etc/profile
sed -i 's/\[ -n "$FAILSAFE" \] && cat \/etc\/banner.failsafe/& || \/usr\/bin\/neofetch/' /etc/profile
if grep -q "ImmortalWrt" /etc/openwrt_release; then
  sed -i "s/\(DISTRIB_DESCRIPTION='ImmortalWrt [0-9]*\.[0-9]*\.[0-9]*\).*'/\1'/g" /etc/openwrt_release
  sed -i -E "s|services/ttyd|system/ttyd|g" /usr/share/ucode/luci/template/themes/material/header.ut
  msg Branch version: "$(grep 'DISTRIB_DESCRIPTION=' /etc/openwrt_release | awk -F"'" '{print $2}')"
elif grep -q "OpenWrt" /etc/openwrt_release; then
  sed -i "s/\(DISTRIB_DESCRIPTION='OpenWrt [0-9]*\.[0-9]*\.[0-9]*\).*'/\1'/g" /etc/openwrt_release
  msg Branch version: "$(grep 'DISTRIB_DESCRIPTION=' /etc/openwrt_release | awk -F"'" '{print $2}')"
fi
msg "###############################################"

# Set hostname and Timezone to Asia/Jakarta
msg "Setup NTP Server and Time Zone to Asia/Jakarta"
uci set system.@system[0].hostname='houjie-WRT'
uci set system.@system[0].timezone='WIB-7'
uci set system.@system[0].zonename='Asia/Jakarta'
uci -q delete system.ntp.server
uci add_list system.ntp.server="pool.ntp.org"
uci add_list system.ntp.server="id.pool.ntp.org"
uci add_list system.ntp.server="time.google.com"
uci commit system



# configure WLAN
msg "Setup Wireless if available"
uci set wireless.@wifi-device[0].disabled='0'
uci set wireless.@wifi-iface[0].disabled='0'
uci set wireless.@wifi-iface[0].encryption='none'
uci set wireless.@wifi-device[0].country='ID'
if grep -q "Raspberry Pi 4\|Raspberry Pi 3" /proc/cpuinfo; then
  uci set wireless.@wifi-iface[0].ssid='houjie-WRT_5g'
  uci set wireless.@wifi-device[0].channel='149'
  uci set wireless.radio0.htmode='HT40'
  uci set wireless.radio0.band='5g'
else
  uci set wireless.@wifi-iface[0].ssid='RTA-WRT_2g'
  uci set wireless.@wifi-device[0].channel='1'
  uci set wireless.@wifi-device[0].band='2g'
fi
uci commit wireless
wifi reload && wifi up
if iw dev | grep -q Interface; then
  if grep -q "Raspberry Pi 4\|Raspberry Pi 3" /proc/cpuinfo; then
    if ! grep -q "wifi up" /etc/rc.local; then
      sed -i '/exit 0/i # remove if you dont use wireless' /etc/rc.local
      sed -i '/exit 0/i sleep 10 && wifi up' /etc/rc.local
    fi
    if ! grep -q "wifi up" /etc/crontabs/root; then
      echo "# remove if you dont use wireless" >> /etc/crontabs/root
      echo "0 */12 * * * wifi down && sleep 5 && wifi up" >> /etc/crontabs/root
      service cron restart
    fi
  fi
else
  msg "No wireless device detected."
fi

# Step 1: Configure Password Login OpenWrt
msg "Step 1: Configure Password Login OpenWrt"
(echo "sijitekowolu"; sleep 1; echo "sijitekowolu") | passwd > /dev/null


# Step 3: Remove login password required when accessing terminal
msg "Step 3: Remove login password required when accessing terminal"
uci set ttyd.@ttyd[0].command='/bin/bash --login'
uci commit ttyd


# Step 4: Remove huawei me909s usb-modeswitch
msg "Step 4: Remove huawei me909s usb-modeswitch"
sed -i -e '/12d1:15c1/,+5d' /etc/usb-mode.json


# Step 5: Remove dw5821e usb-modeswitch
msg "Step 5: Remove dw5821e usb-modeswitch"
sed -i -e '/413c:81d7/,+5d' /etc/usb-mode.json


# Step 6: Disable /etc/config/xmm-modem
msg "Step 6: Disable /etc/config/xmm-modem"
uci set xmm-modem.@xmm-modem[0].enable='0'
uci commit xmm-modem


# Step 7: Setup Nlbwmon Database Dir
msg "Step 7: Setup Nlbwmon Database Dir"
uci set nlbwmon.@nlbwmon[0].database_directory='/etc/nlbwmon'
uci set nlbwmon.@nlbwmon[0].commit_interval='3h'
uci set nlbwmon.@nlbwmon[0].refresh_interval='60s'
uci commit nlbwmon
bash /etc/init.d/nlbwmon restart



# Step 9: Adjusting App Catagory
msg "Step 9: Adjusting App Catagory"
sed -i -E "s|status|services|g" /usr/lib/lua/luci/controller/base64.lua

# Step 14:Default Theme #
msg "Step 14: Set Tema"
uci set luci.main.mediaurlbase='/luci-static/hj' && uci commit



# Step 12: Setup PHP
msg "Step 12: Setup PHP"
msg "system not using php-cgi, patching php config ..."
uci set uhttpd.main.ubus_prefix='/ubus'
uci set uhttpd.main.interpreter='.php=/usr/bin/php-cgi'
uci set uhttpd.main.index_page='cgi-bin/luci'
uci add_list uhttpd.main.index_page='index.html'
uci add_list uhttpd.main.index_page='index.php'
uci commit uhttpd
sed -i -E "s|memory_limit = [0-9]+M|memory_limit = 100M|g" /etc/php.ini
sed -i -E "s|display_errors = On|display_errors = Off|g" /etc/php.ini
ln -s /usr/bin/php-cli /usr/bin/php
[ -d /usr/lib/php8 ] && [ ! -d /usr/lib/php ] && ln -sf /usr/lib/php8 /usr/lib/php
msg "patching system with php configuration done ..."
msg "restarting uhttpd ..."
/etc/init.d/uhttpd restart


# Step 13: Setting Tinyfm
msg "Step 13: Setting Tinyfm"
ln -s / /www/tinyfm/rootfs

# Step 16: Set All permission files
msg "Step 16: Set All permission files"
check_permission() {
    local DIR=${1:-.}

    find "$DIR" -type f | while read file; do
        if file "$file" | grep -q "executable"; then
            if [ ! -x "$file" ]; then
                msg "File requiring chmod +x: $file"
                chmod +x "$file"
            fi
        fi
    done
}

check_permission "/etc/init.d"
check_permission "/etc/mihomo"
check_permission "/etc/openclash"
check_permission "/lib/netifd"
check_permission "/lib/wifi"
check_permission "/sbin"
check_permission "/usr/bin"


# Step 17: Run Another Process
msg "Step 17: Run Another Process"
bash /root/install2.sh


# Step 19: sync_time.sh
msg "Step 19: sync_time.sh Process"
chmod +x /sbin/sync_time.sh
# Log success
msg "First Setup settings successfully applied..."


# Remove this script after successful execution
rm -f /etc/uci-defaults/$(basename $0)
