#!/bin/sh

# ENV
exec > /root/radmon-setup.log 2>&1

msg() {
    local DATE=$(date '+%d %B %Y %T')
    echo "[ INFO RADMON ] $1"
}


# Step 1: Add link Hotspotlogin And radmonMonitor
msg "Step 1: Add link Hotspotlogin And radmonMonitor"
ln -s /usr/share/hotspotlogin /www/hotspotlogin
ln -s /usr/share/Radmonv2 /www/Radmonv2


# Step 2: Configure MySQL / Maridb
msg "Step 1: Configure MySQL / Maridb"
sed -i -E "s|option enabled '0'|option enabled '1'|g" /etc/config/mysqld
sed -i -E "s|# datadir		= /srv/mysql|datadir	= /usr/share/mysql|g" /etc/mysql/conf.d/50-server.cnf
sed -i -E "s|127.0.0.1|0.0.0.0|g" /etc/mysql/conf.d/50-server.cnf
/etc/init.d/mysqld restart
/etc/init.d/mysqld reload
mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('radmon');"
mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'radmon';"
mysql -u root -p"radmon" <<EOF
DELETE FROM mysql.user WHERE User='';
DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db='test' OR Db='test_%';
FLUSH PRIVILEGES;
EOF
mysql -u root -p"radmon" -e "CREATE DATABASE radmon CHARACTER SET utf8";
mysql -u root -p"radmon" -e "GRANT ALL ON radmon.* TO 'radmon'@'localhost' IDENTIFIED BY 'radmon' WITH GRANT OPTION";
mysql -u root -p"radmon" radmon -e "SET FOREIGN_KEY_CHECKS = 0; $(mysql -u root -p"radmon" radmon -e 'SHOW TABLES' | awk '{print "DROP TABLE IF EXISTS `" $1 "`;"}' | grep -v '^Tables' | tr '\n' ' ') SET FOREIGN_KEY_CHECKS = 1;"
#mysql -u root -p"radmon" radmon < /usr/share/radius_monitor.sql
mysql -u root -p"radmon" radmon < /usr/share/Radmonv2/radmon.sql


# Step 3: Configure Freeradius
msg "Step 2: Configure Freeradius"
cd /etc/freeradius3/mods-enabled
ln -s ../mods-available/always
ln -s ../mods-available/attr_filter
ln -s ../mods-available/chap
ln -s ../mods-available/detail
ln -s ../mods-available/digest
ln -s ../mods-available/eap
ln -s ../mods-available/exec
ln -s ../mods-available/expiration
ln -s ../mods-available/expr
ln -s ../mods-available/files
ln -s ../mods-available/logintime
ln -s ../mods-available/mschap
ln -s ../mods-available/pap
ln -s ../mods-available/preprocess
ln -s ../mods-available/radutmp
ln -s ../mods-available/realm
ln -s ../mods-available/sql
ln -s ../mods-available/sradutmp
ln -s ../mods-available/unix
cd /etc/freeradius3/sites-enabled
ln -s ../sites-available/default
ln -s ../sites-available/inner-tunnel


# Step 4: Add Restart Freeradius And Chilli To RC Local
msg "Step 3: Add Restart Freeradius And Chilli To RC Local"
if ! grep -q '/etc/init.d/radiusd restart' /etc/rc.local; then
    sed -i '/exit 0/i /etc/init.d/radiusd restart' /etc/rc.local
fi
chmod +x /etc/init.d/chilli
if ! grep -q '/etc/init.d/chilli restart' /etc/rc.local; then
    sed -i '/exit 0/i /etc/init.d/chilli restart' /etc/rc.local
fi


# Step 5: Configure MySQL / Maridb
msg "Step 1: Configure MySQL / Maridb"
bash /etc/init.d/radiusd restart
bash /etc/init.d/radiusd reload
bash /etc/init.d/chilli restart
bash /etc/init.d/chilli reload


# Log success
msg "Radmon Setup settings successfully applied..."

# Remove this script after successful execution
rm -f /etc/uci-defaults/$(basename $0)